var checkLoading, oneVideoLoaded, showSite, spinOnce, spinnerOn;

$(function() {
  $('menu i').on('click', function() {
    return $(this).parent().toggleClass('opened');
  });
  $('.scrollTo').each(function() {
    return $(this).on('click', function(e) {
      var scrollTo;
      e.preventDefault();
      scrollTo = $(this).attr('href');
      return $('html,body').animate({
        scrollTop: $(scrollTo).offset().top
      }, 1000);
    });
  });
  $(document).on('keydown', function() {
    if (event.which === 27) {
      return $('menu').removeClass('opened');
    }
  });
  return $('body').on('click', function(e) {
    if ($(e.target).parents('menu').length) {
      return e.preventDefault();
    } else if ($(e.target).is('menu')) {
      return e.preventDefault();
    } else {
      return $('menu').removeClass('opened');
    }
  });
});

this.resizeVideo = function() {
  var width;
  width = $('body').width();
  $('.vplayer').attr('width', width / 100 * 89);
  return $('.vplayer').attr('height', (width / 100 * 89) / 1.77);
};

$(function() {
  if ($('.vplayer').length) {
    resizeVideo();
    $(window).resize(function() {
      return resizeVideo();
    });
  }
  $(window).scroll(function(i) {
    var scrollVar, videoBackgroundOpacity, windowHeight;
    windowHeight = $(window).height();
    scrollVar = $(window).scrollTop();
    videoBackgroundOpacity = 1 - scrollVar / windowHeight;
    if (videoBackgroundOpacity >= 0.2) {
      $('#topVideoBackground').css('opacity', videoBackgroundOpacity);
    }
    if (scrollVar / windowHeight >= 4) {
      return $('#topVideoBackground').css('opacity', 0);
    }
  });
  return $('.chevron').on('click', function() {
    return $('html,body').animate({
      scrollTop: $('.video').first().offset().top
    }, 1000);
  });
});

spinOnce = function(current) {
  var next;
  if (current.next().length) {
    next = current.next();
  } else {
    next = current.parent().find('li').first();
  }
  current.toggleClass('current');
  return next.toggleClass('current');
};

spinnerOn = function(spinner) {
  var current;
  current = spinner.find('.current');
  return setTimeout((function() {
    spinOnce(current);
    return spinnerOn($('#preloader'));
  }), 60);
};

showSite = function() {
  $('html').removeClass('preloader');
  return $('#preloader').hide();
};

oneVideoLoaded = function() {
  window.videosLoaded += 1;
  if (window.videosLoaded === 2) {
    return showSite();
  }
};

checkLoading = function(videoId) {
  if ($(videoId)[0].readyState === 4) {
    return oneVideoLoaded();
  } else {
    return setTimeout(function() {
      return checkLoading(videoId);
    }, 100);
  }
};

$(function() {
  if ($('html').hasClass('preloader') && $('html').hasClass('touchno-touch')) {
    window.videosLoaded = 0;
    spinnerOn($('#preloader'));
    checkLoading('#topVideoBackground');
    checkLoading('#registrationVideoBackground');
  }
});

// ---
// generated by coffee-script 1.9.2
